- import_playbook: plays/ansible.yml
- name: vars
  hosts: all
  tasks:
    - name: load vars
      include_vars: group_vars/all.yml
    - name: set server facts
      set_fact:
        dbRootPassword: '!!12345'
        tmcomDBPassword: '!!12345'
        dbBackupPassword: '!!12345'
        tmcomEnv: dev
- import_playbook: plays/main.yml
