- name: site permissions
  become: true
  hosts: all
  tasks:
    - name: site folder ownership
      file:
        group: '{{adminUser}}'
        mode: 'u=rwx,g=rx,o=rx'
        owner: '{{adminUser}}'
        path: /var/www/sites
        recurse: false
- name: prepare tmcom
  become: true
  hosts: all
  tasks:
    - name: set up tmcom db
      mysql_db:
        name: '{{item.value.name}}'
        state: present
      no_log: true
      with_dict: '{{db}}'
    - name: tmcom db user
      mysql_user:
        name: '{{item.value.user}}'
        password: '{{item.value.password}}'
        priv: '{{item.value.name}}.*:ALL'
        state: present
      no_log: true
      with_dict: '{{db}}'
