- name: site permissions
  become: true
  hosts: all
  tasks:
    - name: site folder ownership
      file:
        group: '{{adminUser}}'
        mode: 'u=rwx,g=rx,o=rx'
        owner: '{{adminUser}}'
        path: /var/www/sites
        recurse: false
- name: prepare tmcom
  become: true
  hosts: all
  tasks:
    - name: set up tmcom db
      mysql_db:
        name: tmcom
        state: present
    - name: tmcom db user
      mysql_user:
        name: tmcom
        password: '{{tmcomDBPassword}}'
        priv: 'tmcom.*:ALL'
        state: present
