- name: set up default user
  become: true
  hosts: all
  tasks:
    - name: set default user shell
      lineinfile:
        dest: '/etc/default/useradd'
        line: 'SHELL=/bin/bash'
        regexp: '^SHELL='
        state: present
#--server administrator
- name: set up admin user
  become: true
  hosts: all
  tasks:
    - name: add to staff group
      user:
        append: yes
        groups:
          - staff
        name: '{{adminUser}}'
    - name: install ssh key
      lineinfile:
        dest: '/home/{{adminUser}}/.ssh/authorized_keys'
        line: '{{tmKey}}'
        state: present
#--vagrant
- name: set up vagrant user
  become: true
  hosts: default #-! means vagrant. we should fix this by renaming vagrant box to dev
  tasks:
    #-! we do this because we want to be able to rsync normally, but many of the files are owned by vagrant. we should change them to be owned by adminUser, connect with that user, and then we won't need this
    - name: install ssh key
      lineinfile:
        dest: '/home/vagrant/.ssh/authorized_keys'
        line: '{{tmKey}}'
        state: present
#-!! should have an unprivileged user for owning and editing web files
#--user for accessing from work
- name: set up work user
  become: true
  hosts: [prod, public]
  tasks:
    - name: add work user
      user:
        name: '{{workUser}}'
        state: present
    - name: create work user ssh dir
      file:
        group: '{{workUser}}'
        mode: 0700
        owner: '{{workUser}}'
        path: '/home/{{workUser}}/.ssh'
        state: directory
    - name: create work user keys file
      #-# copy used because 'file' module can't create the file, see <https://stackoverflow.com/a/34929776/1139122>
      copy:
        content: ''
        dest: '/home/{{workUser}}/.ssh/authorized_keys'
        force: no
        group: '{{workUser}}'
        mode: 0600
        owner: '{{workUser}}'
    - name: install work user key
      lineinfile:
        dest: '/home/{{workUser}}/.ssh/authorized_keys'
        line: '{{workKey}}'
        state: present
    - name: install tm ssh key for work
      lineinfile:
        dest: '/home/{{workUser}}/.ssh/authorized_keys'
        line: '{{tmKey}}'
        state: present
