imports:
  - {resource: console.php}
parameters:
  paths.sites: '%paths.project%/sites'
services:
  TJM\ShellRunner\ShellRunner: ~
  TJM\TMCom\Command\:
    autowire: true
    resource: '%paths.project%/src/Command'
    tags: ['console.command']

tjm_console:
  name: 'server-tobymackenzie.com'
  version: '0.1'
