adminUser: ubuntu
backupRootPath: '/var/bu'
backupUser: 'backup'
dbBackupPath: '{{backupRootPath}}/db'
dbBackupUser: 'backup'
fw_allow:
  - { port: 22, proto: tcp }
  - { port: 80, proto: tcp }
  - { port: 443, proto: tcp }
  - { port: 2784, proto: tcp } # original http port
serverName: 'tobymackenzie.com'
sites:
  tobymackenzie.com:
    accessLog: tmpublic
    https: true
    httpsCert: tobymackenzie.com
    name: www.tobymackenzie.com
    aliases:
      - t.www.tobymackenzie.com
    webroot: /tobymackenzie.com/dist/public/
    sort: 0
  dev.tobymackenzie.com:
    accessLog: tmdev
    aliases:
      - t.dev.tobymackenzie.com
    https: true
    httpsCert: dev.tobymackenzie.com
    webroot: /dev.tobymackenzie.com
  short:
    accessLog: short
    https: true
    httpsCert: tobymackenzie.com
    webroot: /tobymackenzie.com/dist/short/
  public-alias:
    accessLog: tmpublic
    aliases:
      - 'tobymackenzie.com'
      - '*.tobymackenzie.com'
      - me.tobymackenzie.com
      - personal.tobymackenzie.com
      - webd.tobymackenzie.com
      - '*.tobymackenzie.name'
      - www.tobymackenzie.name
    https: true
    httpsCert: tobymackenzie.com
    name: tobymackenzie.name
    redirect: 'www.tobymackenzie.com'
    sort: 2
tmKey: 'ssh-rsa !!12345 admin@tobymackenzie.com'
tmcomEnv: 'prod'
workKey: 'ssh-rsa !!12345 admin@tobymackenzie.com'
workUser: wrk
