adminUser: ubuntu
backupRootPath: '/var/bu'
backupUser: 'backup'
dbBackupPath: '{{backupRootPath}}/db'
dbBackupUser: 'backup'
defaultSite: 'tobymackenzie.com'
fw_allow:
  - { port: 22, proto: tcp }
  - { port: 80, proto: tcp }
  - { port: 443, proto: tcp }
sites:
  tobymackenzie.com:
    https: true
    name: www.tobymackenzie.com
    aliases:
      - t.www.tobymackenzie.com
    webroot: /web/
  dev.tobymackenzie.com:
    aliases:
      - t.dev.tobymackenzie.com
    https: true
    webroot: /
  public-alias:
    aliases:
      - 'tobymackenzie.com'
      - '*.tobymackenzie.com'
      - me.tobymackenzie.com
      - personal.tobymackenzie.com
      - webd.tobymackenzie.com
      - '*.tobymackenzie.name'
      - www.tobymackenzie.name
    name: tobymackenzie.name
    redirect: 'www.tobymackenzie.com'
tmKey: 'ssh-rsa !!12345 admin@tobymackenzie.com'
tmcomEnv: 'prod'
workKey: 'ssh-rsa !!12345 admin@tobymackenzie.com'
workUser: wrk
